### ISSUE TITLE
Error after an update

### ISSUE THREAD

**Issue by lionel-m** [westwerk/contao-eventsubscribe#2]
```
Fatal error: Class 'tl_calendar_events_ext' not found in /Applications/MAMP/htdocs/develop/system/modules/eventsubscribe/dca/tl_calendar_events.php on line 12
```

**Comment by tb-now** [comment]
I just tested it with an update on an other test-server, but I don't get the error. Where do you get the error? And did you rebuild your cache?

**Comment by tim-bec** [comment]
@lionel-m - which contao version?
and what do you exactly updated? just an event? the extension?

**Comment by lionel-m** [comment]
Tested with the develop branch and a version 3.1.0 stable.

> did you rebuild your cache

Yes.

Could you make an update of the database in the BE `Extension manager -> update database` ? I get the problem with this action for example.

**Comment by tb-now** [comment]
Hm, that's strange. I don't get there any error. I just tested it with a 3.1.0 and a 3.1.2 version. I'm sorry for your problems with that extension, but I can't reproduce the error ...

**Comment by tb-now** [comment]
I reworked the part, it should be fixed :)

**Comment by lionel-m** [comment]
Perfect ! Thanks
